// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Migrations
{
    [DbContext(typeof(ShortlinkContext))]
    [Migration("20230316012647_Shortlink")]
    partial class Shortlink
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Entities.Shortlink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Hint")
                        .HasColumnType("integer");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shortlink");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a372f58e-9486-4780-b2ae-3239cb993732"),
                            CreatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Deleted = false,
                            Hint = 5,
                            ShortUrl = "http://chr.dc/9dtr4",
                            UpdatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Url = "http://globo.com"
                        },
                        new
                        {
                            Id = new Guid("b45ca260-1c9f-49b2-b34c-92495970cf41"),
                            CreatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Deleted = false,
                            Hint = 4,
                            ShortUrl = "http://chr.dc/aUx71",
                            UpdatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Url = "http://google.com"
                        },
                        new
                        {
                            Id = new Guid("01ae31f2-fa83-4c01-846f-1b04ba338593"),
                            CreatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Deleted = false,
                            Hint = 7,
                            ShortUrl = "http://chr.dc/u9jh3",
                            UpdatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Url = "http://terra.com.br"
                        },
                        new
                        {
                            Id = new Guid("b701d6f9-6efc-4c51-82a0-5ec16bca505a"),
                            CreatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Deleted = false,
                            Hint = 1,
                            ShortUrl = "http://chr.dc/qy61p",
                            UpdatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Url = "http://facebook.com"
                        },
                        new
                        {
                            Id = new Guid("9153f2f7-76fe-44d7-b280-f89516382b46"),
                            CreatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Deleted = false,
                            Hint = 2,
                            ShortUrl = "http://chr.dc/87itr",
                            UpdatedAt = new DateTime(2023, 3, 15, 22, 26, 47, 467, DateTimeKind.Local).AddTicks(3201),
                            Url = "http://diariocatarinense.com.br"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
